### ISSUE TITLE
mac运行报错

### ISSUE THREAD

**Issue by T4y1oR** [Mustard404/Auto_proxy#1]
<img width="260" alt="image" src="https://user-images.githubusercontent.com/85985129/167367061-be9b7aeb-85e4-4adf-b5bd-168fbb210592.png">

mac 在clash文件夹下运行的py ,clash选择auto_proxy时报错

**Comment by Mustard404** [comment]
https://http.py.cn/api/
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/14071947/167397550-49aaed31-417b-4b5f-84de-231dc8ab024e.png">

**Comment by Mustard404** [comment]
白名单
