### ISSUE TITLE
win环境出现问题

### ISSUE THREAD

**Issue by admin-set** [Mustard404/Auto_proxy#3]

**Comment by Mustard404** [comment]
calsh不要关闭并通过浏览器访问品易接口，是不是提示白名单错误

**Comment by admin-set** [comment]
不是特别明白 啥叫做关闭浏览器访问品易接口。指的是 ClashX 配置代理白名单 吗？

**Comment by Mustard404** [comment]
嗯，你试下这个原因。先通过clash代理访问下品易接口，看下返回信息

**Comment by admin-set** [comment]
![image](https://user-images.githubusercontent.com/63496176/172333174-d19de6e9-f783-4f43-b1e8-1b774c25bd9f.png)
错误方法和上面是一样的
